name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies Frontend
        run: |
          npm install
        
      - name: Start Frontend Server
        run: |
          npm install
          npm run build 
          npm run start &
        env:
          NODE_ENV: test

      - name: Run Cypress Tests
        run: |
          npm run test
